name= "yAmini"
print(name)
print(len(name))
print(name.endswith("ini"))
print(name.startswith("yA"))
print(name.capitalize())
print(name.upper())
print(name.lower())
print(name.title())
print(name.swapcase())
print(name.isalpha())
print(name.isdigit())
print(name.isalnum())
print(name.islower())
print(name.isupper())